# Generated by Django 4.1.1 on 2022-09-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Livro",
            fields=[
                ("id_livro", models.AutoField(primary_key=True, serialize=False)),
                ("sinopse_livro", models.CharField(max_length=1000)),
                ("titulo_livro", models.CharField(max_length=100)),
                ("qtd_paginas", models.PositiveIntegerField()),
                ("ano_lancamento", models.DateField()),
                ("url_compra", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nome_usuario", models.CharField(max_length=60)),
                ("data_nasc", models.DateField()),
                ("telefone_user", models.PositiveIntegerField()),
                ("endereco_usuario", models.CharField(max_length=100)),
                ("cpf", models.PositiveIntegerField()),
                ("email_user", models.EmailField(max_length=254)),
                ("senha_user", models.CharField(max_length=20)),
                ("adm", models.BooleanField()),
            ],
        ),
    ]
