# Generated by Django 4.1.1 on 2022-09-07 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resenha",
            name="nota_resenha",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ]
            ),
        ),
    ]
