# Generated by Django 4.1.1 on 2022-10-04 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resenha",
            name="user_resenha",
        ),
        migrations.AddField(
            model_name="resenha",
            name="user_resenha",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resenha",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
