# Generated by Django 4.1.1 on 2022-09-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="capa_livro",
            field=models.FileField(upload_to=""),
        ),
    ]
