# Generated by Django 4.1.1 on 2022-09-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="foto_perfil",
            field=models.FileField(upload_to="fotoperfil/"),
        ),
    ]
