# Generated by Django 4.1.1 on 2022-10-03 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resenha",
            name="user_lista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resenhado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
