# Generated by Django 4.1.1 on 2022-09-30 01:42

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=cpf_field.models.CPFField(max_length=14),
        ),
    ]
