# Generated by Django 4.1.1 on 2022-09-07 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livro",
            old_name="autor_livro",
            new_name="autor_li",
        ),
    ]
