# Generated by Django 4.1.1 on 2022-09-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="data_nasc",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="endereco_user",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="foto_perfil",
            field=models.ImageField(blank=True, upload_to="fotoperfil/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="telefone_user",
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
