# Generated by Django 4.1.1 on 2022-09-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resenha",
            old_name="livro_resenha",
            new_name="livro_res",
        ),
    ]
