# Generated by Django 4.1.1 on 2022-09-18 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_cpf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name_plural": "Usuarios"},
        ),
    ]
