# Generated by Django 4.1.1 on 2022-10-04 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_resenha_user_resenha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resenha",
            name="user_resenha",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resenha",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
