# Generated by Django 4.1.1 on 2022-09-07 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_autor_livro_livro_autor_li"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livro",
            old_name="autor_li",
            new_name="autor_livros",
        ),
    ]
