# Generated by Django 4.1.1 on 2022-09-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_livro_sinopse_livro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="sinopse_livro",
            field=models.CharField(max_length=1000),
        ),
    ]
