# Generated by Django 4.1.1 on 2022-09-30 01:45

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=cpf_field.models.CPFField(max_length=14, verbose_name="cpf"),
        ),
    ]
