# Generated by Django 4.1.1 on 2022-09-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_data_nasc_alter_user_endereco_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="data_nasc",
            field=models.DateField(blank=True, null=True),
        ),
    ]
