# Generated by Django 4.1.1 on 2022-09-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_autor_li_livro_autor_livros"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="categoria_livro",
            field=models.ManyToManyField(related_name="livros", to="core.categoria"),
        ),
    ]
