# Generated by Django 4.1.2 on 2022-11-25 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_user_imagem_midia"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="medianota",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resenha",
            name="livro_resenha",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resenha",
                to="core.livro",
            ),
        ),
        migrations.AlterField(
            model_name="resenha",
            name="user_resenha",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resenha",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
