# Generated by Django 4.1.1 on 2022-09-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_livro_sinopse_livro"),
    ]

    operations = [
        migrations.CreateModel(
            name="categoria",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                ("nome_categoria", models.CharField(max_length=30)),
                ("desc_categoria", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="livro",
            name="sinopse_livro",
            field=models.TextField(),
        ),
    ]
