# Generated by Django 4.1.1 on 2022-09-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_livro_res_resenha_livro_opniao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resenha",
            old_name="livro_opniao",
            new_name="livro_resenha",
        ),
    ]
