# Generated by Django 4.1.1 on 2022-09-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_categoria_alter_livro_sinopse_livro"),
    ]

    operations = [
        migrations.CreateModel(
            name="autor",
            fields=[
                ("id_autor", models.AutoField(primary_key=True, serialize=False)),
                ("nome_autor", models.CharField(max_length=60)),
                ("desc_autor", models.TextField()),
                ("autor_nasc", models.DateField()),
                ("autor_falecimento", models.DateField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Autores",
            },
        ),
    ]
