# Generated by Django 4.1.1 on 2022-09-21 19:54

from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_telefone_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editora",
            name="cnpj",
            field=django_cpf_cnpj.fields.CNPJField(max_length=18),
        ),
        migrations.AlterField(
            model_name="user",
            name="telefone_user",
            field=models.CharField(max_length=11),
        ),
    ]
