# Generated by Django 4.1.1 on 2022-09-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_autor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="autor_falecimento",
            field=models.IntegerField(blank=True),
        ),
    ]
