# Generated by Django 4.1.2 on 2022-11-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_livro_medianota"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="autor_imagem",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
