# Generated by Django 4.1.1 on 2022-09-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_autor_autor_falecimento"),
    ]

    operations = [
        migrations.CreateModel(
            name="editora",
            fields=[
                ("id_editora", models.AutoField(primary_key=True, serialize=False)),
                ("nome_editora", models.CharField(max_length=100)),
                ("desc_editora", models.TextField()),
                ("cnpj", models.PositiveIntegerField()),
                ("endereco_editora", models.CharField(max_length=150)),
                ("email_editora", models.EmailField(max_length=254)),
                ("senha_editora", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="autor",
            name="autor_falecimento",
            field=models.DateField(null=True),
        ),
    ]
