# Generated by Django 4.1.2 on 2022-11-26 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_autor_autor_imagem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listafav",
            name="desc_lista",
        ),
        migrations.AlterField(
            model_name="listafav",
            name="livros_lista",
            field=models.ManyToManyField(
                blank=True, related_name="lista_livro", to="core.livro"
            ),
        ),
        migrations.AlterField(
            model_name="listafav",
            name="user_lista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Lista",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
