# Generated by Django 4.1.2 on 2022-11-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_listafav_desc_lista_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="medianota",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
