# Generated by Django 4.1.2 on 2022-11-27 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_livro_medianota"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cnpj",
            field=django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name="user",
            name="is_editora",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="livro",
            name="editora_livro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="livros",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="editora",
        ),
    ]
