# Generated by Django 4.1.2 on 2022-11-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_livro_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="biografia",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
